name: Android CI/CD

on:
  push:
    branches:
      - "**" # chạy trên mọi nhánh
  pull_request:
    branches:
      - "**"

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --stacktrace

  build:
    name: Build APK
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

  deploy:
    name: Deploy if on develop branch
    needs: [build]
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: Build APK for Develop
        run: ./gradlew assembleDevelopDebug

      - name: Upload to Firebase (Fastlane)
        run: |
          gem install fastlane
          fastlane android distribute_firebase
