name: Flutter Android CI/CD

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      - name: Grant execute permission
        run: chmod +x gradlew
        working-directory: android

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --stacktrace
        working-directory: android

  build_debug:
    name: Build Debug APK
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      - name: Grant execute permission
        run: chmod +x gradlew
        working-directory: android

      - name: Build Debug APK
        run: ./gradlew assembleDebug
        working-directory: android

      - uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

  deploy:
    name: Deploy to Firebase (develop branch)
    needs: [build_debug]
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      - name: Grant execute permission
        run: chmod +x gradlew
        working-directory: android

      - name: Build APK for Develop
        run: ./gradlew assembleDevelopDebug
        working-directory: android

      - name: Install Fastlane and Deploy
        run: |
          gem install fastlane
          fastlane android distribute_firebase
