name: Flutter Android CI/CD

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: "34.0.0"

      # - name: Grant execute permission to Gradle
      #   run: chmod +x ./gradlew

      # - name: Run Unit Tests
      #   run: ./gradlew testDebugUnitTest --stacktrace

  build_debug:
    name: Build Debug APK
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: "34.0.0"

      # - name: Grant execute permission to Gradle
      #   run: chmod +x ./gradlew

      # - name: Build Debug APK
      #   run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

  build_release:
    name: Build Release APK
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: "34.0.0"

      # - name: Grant execute permission to Gradle
      #   run: chmod +x ./gradlew

      # - name: Build Release APK
      #   run: ./gradlew assembleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk

  # deploy:
  #   name: Deploy to Firebase (develop branch)
  #   needs: [build_release]
  #   if: github.ref == 'refs/heads/develop'
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout source code
  #       uses: actions/checkout@v4

  #     - name: Set up JDK 21
  #       uses: actions/setup-java@v4
  #       with:
  #         java-version: "21"
  #         distribution: "temurin"

  #     - name: Setup Android SDK
  #       uses: android-actions/setup-android@v2
  #       with:
  #         api-level: 34
  #         build-tools: "34.0.0"

  #     # - name: Grant execute permission to Gradle
  #     #   run: chmod +x ./gradlew

  #     # - name: Build APK for Develop
  #     #   run: ./gradlew assembleDevelopDebug

  #     - name: Install Fastlane and Deploy to Firebase
  #       run: |
  #         gem install fastlane
  #         fastlane android distribute_firebase
