name: Flutter Android CI/CD

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: '34.0.0'

      - name: Grant execute permission to Gradle
        run: chmod +x gradlew
        working-directory: android

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --stacktrace
        working-directory: android

  build_debug:
    name: Build Debug APK
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: '34.0.0'

      - name: Grant execute permission
        run: chmod +x gradlew
        working-directory: android

      - name: Build Debug APK
        run: ./gradlew assembleDebug
        working-directory: android

      - uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

  build_release:
    name: Build Release APK
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: '34.0.0'

      - name: Grant execute permission
        run: chmod +x gradlew
        working-directory: android

      - name: Build Release APK
        run: ./gradlew assembleRelease
        working-directory: android

      - uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
